// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://kfyjouusitqzbgijjrgc.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeWpvdXVzaXRxemJnaWpqcmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4OTQ5MjUsImV4cCI6MjA4OTQ3MDkyNX0.clhNzTBPgpQHqZ_tC89WNl-yN6Ow_Namib4SIJznF5U';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});